In [3]:
import pandas

In [4]:
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pandas.read_csv(url, names=names)

In [6]:
array = dataset.values
X = array[:,0:4]
Y = array[:,4]
validation_size = 0.20
seed = 7

In [8]:
import sklearn

In [10]:
seed = 7
scoring = 'accuracy'

In [13]:
from sklearn import model_selection

In [14]:
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [16]:
X_train

array([[6.2, 2.8, 4.8, 1.8],
       [5.7, 2.6, 3.5, 1.0],
       [4.6, 3.6, 1.0, 0.2],
       [6.9, 3.1, 5.4, 2.1],
       [6.4, 2.9, 4.3, 1.3],
       [4.8, 3.0, 1.4, 0.3],
       [5.5, 3.5, 1.3, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [7.1, 3.0, 5.9, 2.1],
       [6.7, 3.3, 5.7, 2.1],
       [6.8, 2.8, 4.8, 1.4],
       [6.4, 2.8, 5.6, 2.2],
       [6.5, 3.0, 5.5, 1.8],
       [5.7, 3.0, 4.2, 1.2],
       [5.0, 3.3, 1.4, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [6.0, 2.2, 4.0, 1.0],
       [6.4, 2.7, 5.3, 1.9],
       [4.7, 3.2, 1.6, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.3, 3.0, 1.1, 0.1],
       [6.3, 3.3, 6.0, 2.5],
       [5.5, 2.4, 3.7, 1.0],
       [5.0, 2.0, 3.5, 1.0],
       [6.5, 2.8, 4.6, 1.5],
       [5.0, 3.4, 1.6, 0.4],
       [4.4, 2.9, 1.4, 0.2],
       [5.0, 3.5, 1.6, 0.6],
       [6.7, 3.1, 4.7, 1.5],
       [7.3, 2.9, 6.3, 1.8],
       [5.5, 2.6, 4.4, 1.2],
       [5.2, 2

In [20]:
import sys
import scipy
import numpy
import matplotlib
import sklearn
import pandas

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [22]:
# Spot Check Algorithms
models = []
models.append(('KNN', KNeighborsClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

KNN: 0.983333 (0.033333)
NB: 0.975000 (0.053359)
SVM: 0.991667 (0.025000)


c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:

In [28]:
# Make predictions on validation dataset
svm = SVC()
svm.fit(X_train, Y_train)
predictions = svm.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

0.9333333333333333
[[ 7  0  0]
 [ 0 10  2]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      0.83      0.91        12
 Iris-virginica       0.85      1.00      0.92        11

       accuracy                           0.93        30
      macro avg       0.95      0.94      0.94        30
   weighted avg       0.94      0.93      0.93        30



c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report