In [9]:
import sys
import scipy
import numpy
import matplotlib
import sklearn
import pandas

In [10]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/haberman/haberman.data"
names = ['age', 'year', 'positive-axilliary', 'class']
dataset = pandas.read_csv(url, names=names)

In [11]:
array = dataset.values
X = array[:,0:4]
Y = array[:,3]
validation_size = 0.20
seed = 7
from sklearn import model_selection
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [12]:
seed = 7
scoring = 'accuracy'

In [15]:
X_train

array([[66, 58,  0,  1],
       [38, 66,  0,  1],
       [52, 60,  5,  1],
       [54, 65, 23,  2],
       [56, 66,  2,  1],
       [46, 58,  3,  1],
       [49, 66,  0,  1],
       [45, 64,  0,  1],
       [72, 63,  0,  2],
       [65, 58,  0,  2],
       [48, 62,  2,  1],
       [54, 67, 46,  1],
       [45, 67,  0,  1],
       [61, 59,  0,  1],
       [38, 69, 21,  2],
       [69, 60,  0,  1],
       [43, 58, 52,  2],
       [62, 65, 19,  2],
       [44, 61,  0,  1],
       [47, 61,  0,  1],
       [41, 69,  8,  1],
       [50, 59,  0,  1],
       [64, 61,  0,  1],
       [64, 66,  0,  1],
       [42, 63,  1,  1],
       [54, 62,  0,  1],
       [55, 69, 22,  1],
       [43, 60,  0,  1],
       [39, 67,  0,  1],
       [40, 58,  2,  1],
       [52, 63,  4,  1],
       [34, 61, 10,  1],
       [62, 58,  0,  2],
       [63, 60,  1,  2],
       [55, 68, 15,  2],
       [52, 68,  0,  1],
       [51, 66,  1,  1],
       [47, 65,  0,  2],
       [53, 60,  2,  1],
       [41, 58,  0,  1],


In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [17]:
# Spot Check Algorithms
models = []
models.append(('KNN', KNeighborsClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)
	
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

KNN: 0.750333 (0.075854)
NB: 1.000000 (0.000000)


c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:

SVM: 0.738167 (0.085653)


c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [18]:
# Make predictions on validation dataset
svm = SVC()
svm.fit(X_train, Y_train)
predictions = svm.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

0.7741935483870968
[[45  0]
 [14  3]]
              precision    recall  f1-score   support

           1       0.76      1.00      0.87        45
           2       1.00      0.18      0.30        17

    accuracy                           0.77        62
   macro avg       0.88      0.59      0.58        62
weighted avg       0.83      0.77      0.71        62



c:\users\linggarm\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [19]:
# Make predictions on validation dataset
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, Y_train)
predictions = nb.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

1.0
[[45  0]
 [ 0 17]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        45
           2       1.00      1.00      1.00        17

    accuracy                           1.00        62
   macro avg       1.00      1.00      1.00        62
weighted avg       1.00      1.00      1.00        62

